"""
email_sender.py
===============
RPA Module: Email Sender
Sends (or mocks) welcome emails to new employees.

EmailMode (from Config.xlsx):
  "mock"  → prints email to console & saves to Logs/MockEmails/
  "smtp"  → actually sends via SMTP (requires SenderEmail + SenderPassword in config)
"""

import os
import logging
from datetime import datetime

logger = logging.getLogger("RPA_Onboarding")


def _format_date(date_str: str) -> str:
    try:
        from datetime import datetime as dt
        return dt.strptime(date_str, "%Y-%m-%d").strftime("%d %B %Y")
    except Exception:
        return date_str


def build_email_body(employee_data: dict, company_name: str) -> str:
    """Returns the plain-text body of the welcome email."""
    emp_id      = employee_data.get("employee_id", "N/A")
    full_name   = employee_data.get("full_name", "Employee")
    department  = employee_data.get("department", "N/A")
    designation = employee_data.get("designation", "N/A")
    doj         = _format_date(employee_data.get("date_of_joining", ""))
    manager     = employee_data.get("manager_name", "N/A")
    email       = employee_data.get("email", "")

    return f"""Dear {full_name},

Welcome to {company_name}!

We are thrilled to have you join our growing family. This email confirms your successful onboarding and provides your key employment details.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  YOUR EMPLOYMENT DETAILS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Employee ID     : {emp_id}
  Full Name       : {full_name}
  Department      : {department}
  Designation     : {designation}
  Date of Joining : {doj}
  Reporting To    : {manager}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Please find your Welcome Letter attached to this email.

On your first day, please bring:
  ✓ Government-issued photo ID (Aadhaar / Passport / Driving License)
  ✓ Address proof
  ✓ Educational qualification certificates
  ✓ 2 passport-size photographs
  ✓ Bank account details for salary processing

If you have any questions before your joining date, feel free to contact the HR Department.

We look forward to a wonderful journey together!

Warm regards,
HR Department
{company_name}

─────────────────────────────────────────────────────
This is an automated email generated by the Employee Onboarding System.
Please do not reply to this email.
─────────────────────────────────────────────────────
"""


def build_email_html(employee_data: dict, company_name: str) -> str:
    """Returns an HTML version of the welcome email."""
    emp_id      = employee_data.get("employee_id", "N/A")
    full_name   = employee_data.get("full_name", "Employee")
    department  = employee_data.get("department", "N/A")
    designation = employee_data.get("designation", "N/A")
    doj         = _format_date(employee_data.get("date_of_joining", ""))
    manager     = employee_data.get("manager_name", "N/A")

    return f"""<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    body {{ font-family: Arial, sans-serif; background: #f4f6f9; margin: 0; padding: 20px; }}
    .card {{ background: white; max-width: 600px; margin: auto; border-radius: 12px;
             box-shadow: 0 4px 20px rgba(0,0,0,0.1); overflow: hidden; }}
    .header {{ background: linear-gradient(135deg, #1E3A5F, #2E6DA4); color: white;
               padding: 30px 40px; text-align: center; }}
    .header h1 {{ margin: 0; font-size: 26px; }}
    .header p  {{ margin: 6px 0 0; opacity: 0.85; font-size: 13px; }}
    .body  {{ padding: 30px 40px; }}
    .body p {{ color: #444; line-height: 1.7; }}
    .details-table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
    .details-table td {{ padding: 10px 14px; font-size: 14px; border-bottom: 1px solid #eee; }}
    .details-table td:first-child {{ background: #1E3A5F; color: white; font-weight: bold;
                                     width: 40%; border-radius: 0; }}
    .details-table td:last-child  {{ background: #EEF3F8; color: #333; }}
    .checklist {{ background: #f9f9f9; border-left: 4px solid #C9A84C; padding: 14px 20px;
                  border-radius: 4px; margin: 20px 0; }}
    .checklist li {{ color: #555; margin: 6px 0; }}
    .footer {{ background: #1E3A5F; color: rgba(255,255,255,0.6); text-align: center;
               padding: 16px; font-size: 11px; }}
  </style>
</head>
<body>
  <div class="card">
    <div class="header">
      <h1>🎉 Welcome to {company_name}!</h1>
      <p>We are excited to have you on board.</p>
    </div>
    <div class="body">
      <p>Dear <strong>{full_name}</strong>,</p>
      <p>Congratulations on joining <strong>{company_name}</strong>! 
         This email confirms your successful onboarding and provides your key employment details.</p>

      <table class="details-table">
        <tr><td>Employee ID</td>   <td>{emp_id}</td></tr>
        <tr><td>Full Name</td>     <td>{full_name}</td></tr>
        <tr><td>Department</td>    <td>{department}</td></tr>
        <tr><td>Designation</td>   <td>{designation}</td></tr>
        <tr><td>Date of Joining</td><td>{doj}</td></tr>
        <tr><td>Reporting To</td>  <td>{manager}</td></tr>
      </table>

      <p>Please bring the following documents on your first day:</p>
      <div class="checklist">
        <ul>
          <li>Government-issued photo ID (Aadhaar / Passport / Driving License)</li>
          <li>Address proof</li>
          <li>Educational qualification certificates</li>
          <li>2 passport-size photographs</li>
          <li>Bank account details for salary processing</li>
        </ul>
      </div>

      <p>Your Welcome Letter is attached to this email. Please review it carefully.</p>
      <p>If you have any questions, feel free to reach out to the HR Department.</p>
      <p>We look forward to a wonderful journey together! 🚀</p>
      <p>Warm regards,<br><strong>HR Department</strong><br>{company_name}</p>
    </div>
    <div class="footer">
      This is an automated email from the Employee Onboarding System. Please do not reply.
    </div>
  </div>
</body>
</html>"""


def send_welcome_email(employee_data: dict, config: dict,
                        attachment_path: str = None) -> dict:
    """
    Sends (or mocks) a welcome email to the new employee.

    Args:
        employee_data: Dict with employee fields + employee_id
        config: Dict from Config.xlsx (read via excel_handler.read_config)
        attachment_path: Optional path to the welcome letter PDF to attach

    Returns:
        {"success": True/False, "mode": "mock"/"smtp", "error": "..."}
    """
    email_mode   = config.get("EmailMode", "mock").lower()
    company_name = config.get("CompanyName", "ABC Technologies")
    emp_id       = employee_data.get("employee_id", "N/A")
    to_email     = employee_data.get("email", "")
    full_name    = employee_data.get("full_name", "Employee")

    subject = config.get("EmailSubject", "Welcome to {CompanyName} - {EmployeeID}")
    subject = subject.replace("{CompanyName}", company_name).replace("{EmployeeID}", emp_id)

    body_text = build_email_body(employee_data, company_name)
    body_html = build_email_html(employee_data, company_name)

    # ── Mock Mode ──────────────────────────────────────────────────────────────
    if email_mode == "mock":
        try:
            mock_dir = os.path.join("Logs", "MockEmails")
            os.makedirs(mock_dir, exist_ok=True)
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            mock_file = os.path.join(mock_dir, f"Email_{emp_id}_{timestamp}.txt")

            with open(mock_file, "w", encoding="utf-8") as f:
                f.write(f"TO      : {to_email}\n")
                f.write(f"FROM    : HR Department <{config.get('SenderEmail', 'hr@abc.com')}>\n")
                f.write(f"SUBJECT : {subject}\n")
                f.write(f"DATE    : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
                f.write(f"ATTACH  : {attachment_path or 'None'}\n")
                f.write("─" * 60 + "\n")
                f.write(body_text)

            logger.info(f"[MOCK EMAIL] Saved to {mock_file}")
            print(f"\n{'='*60}")
            print(f"  📧 MOCK EMAIL — {emp_id} ({full_name})")
            print(f"{'='*60}")
            print(f"  TO:      {to_email}")
            print(f"  SUBJECT: {subject}")
            print(f"  MODE:    Mock (no real email sent)")
            print(f"  SAVED:   {mock_file}")
            print(f"{'='*60}\n")

            return {"success": True, "mode": "mock", "error": None, "saved_path": mock_file}
        except Exception as e:
            msg = f"Failed to save mock email for {emp_id}: {e}"
            logger.error(msg)
            return {"success": False, "mode": "mock", "error": msg}

    # ── SMTP Mode ──────────────────────────────────────────────────────────────
    elif email_mode == "smtp":
        try:
            import smtplib
            from email.mime.multipart import MIMEMultipart
            from email.mime.text import MIMEText
            from email.mime.base import MIMEBase
            from email import encoders

            smtp_server   = config.get("SMTPServer", "smtp.gmail.com")
            smtp_port     = int(config.get("SMTPPort", 587))
            sender_email  = config.get("SenderEmail", "")
            sender_pass   = config.get("SenderPassword", "")

            if not sender_email or not sender_pass:
                raise ValueError("SenderEmail and SenderPassword must be set in Config.xlsx for SMTP mode.")

            msg = MIMEMultipart("alternative")
            msg["Subject"] = subject
            msg["From"]    = f"HR Department <{sender_email}>"
            msg["To"]      = to_email

            msg.attach(MIMEText(body_text, "plain"))
            msg.attach(MIMEText(body_html, "html"))

            # Attach PDF if provided
            if attachment_path and os.path.exists(attachment_path):
                with open(attachment_path, "rb") as f:
                    part = MIMEBase("application", "octet-stream")
                    part.set_payload(f.read())
                encoders.encode_base64(part)
                part.add_header(
                    "Content-Disposition",
                    f"attachment; filename={os.path.basename(attachment_path)}"
                )
                msg.attach(part)

            with smtplib.SMTP(smtp_server, smtp_port) as server:
                server.ehlo()
                server.starttls()
                server.login(sender_email, sender_pass)
                server.sendmail(sender_email, to_email, msg.as_string())

            logger.info(f"Welcome email sent via SMTP to {to_email} for {emp_id}")
            return {"success": True, "mode": "smtp", "error": None}

        except Exception as e:
            msg = f"SMTP email failed for {emp_id}: {e}"
            logger.error(msg)
            return {"success": False, "mode": "smtp", "error": msg}

    else:
        msg = f"Unknown EmailMode '{email_mode}'. Use 'mock' or 'smtp'."
        logger.error(msg)
        return {"success": False, "mode": email_mode, "error": msg}
